### ISSUE TITLE
Error 500 after loggin in with Trello

### ISSUE THREAD

**Issue by rollsappletree** [francois2metz/trello-calendar#15]
on the browser i have "error" printed on screen and from developer tools i see it return a error 500.

From the cmd instead i have:

    making recursive /root/trello-calendar/builtAssets/css
    TypeError: /root/trello-calendar/lib/views/layout.jade:8
        6|     meta(name="viewport", content="width=device-width, initial-scale=1.0")
        7|     meta(name="apple-mobile-web-app-capable", content="yes")
      > 8|     != css('base')
        9|     link(rel="icon", type="image/png", href="favicon.png")
        10|     link(rel="apple-touch-icon", sizes="57x57", href="img/apple-touch-icon-57x57.png")
        11|     link(rel="apple-touch-icon", sizes="114x114", href="img/apple-touch-icon-114x114.png")

   undefined is not a function
      at mkdirRecursive (/root/trello-calendar/node_modules/connect-assets/lib/assets.js:566:14)
      at ConnectAssets.compileCSS (/root/trello-calendar/node_modules/connect-assets    /lib/assets.js:305:15)
      at context.css (/root/trello-calendar/node_modules/connect-assets/lib/assets.js:119:51)
      at eval (<anonymous>:37:15)
      at Object.<anonymous> (/root/trello-calendar/node_modules/jade/lib/jade.js:165:12)
      at ServerResponse.res._render (/root/trello-calendar/node_modules/express/lib/view.js:425:21)
      at ServerResponse.res.render (/root/trello-calendar/node_modules/express/lib/view.js:318:17)
      at ServerResponse.res._render (/root/trello-calendar/node_modules/express/lib/view.js:432:10)
      at ServerResponse.res.render (/root/trello-calendar/node_modules/express/lib/view.js:318:17)
      at /root/trello-calendar/lib/app.js:29:17
      at callbacks (/root/trello-calendar/node_modules/express/lib/router/index.js:272:11)
      at param (/root/trello-calendar/node_modules/express/lib/router/index.js:246:11)
      at pass (/root/trello-calendar/node_modules/express/lib/router/index.js:253:5)
      at Router._dispatch (/root/trello-calendar/node_modules/express/lib/router/index.js:280:5)
      at Object.Router.middleware [as handle] (/root/trello-calendar/node_modules/express/lib/router    /index.js:45:10)
      at next (/root/trello-calendar/node_modules/express/node_modules/connect/lib/http.js:204:15)
      at /root/trello-calendar/node_modules/connect-assets/node_modules/connect-file-cache            /lib/cache.js:46:18
  at ConnectFileCache.loadFile (/root/trello-calendar/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:54:37)
  at ConnectFileCache.middleware (/root/trello-calendar/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:40:19)
  at Object.handle (/root/trello-calendar/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:3:63)
  at next (/root/trello-calendar/node_modules/express/node_modules/connect/lib/http.js:204:15)
  at /root/trello-calendar/node_modules/express/node_modules/connect/lib/middleware/static.js:150:11
  at FSReqWrap.oncomplete (fs.js:99:15)

**Comment by towfiq** [comment]
Try running `npm build` first -- I was having the same problem and then that worked for me.

**Comment by mfissehaye** [comment]
Same problem. Running npm build doesn't seem to solve the problem

**Comment by CanKattwinkel** [comment]
Since the hosted Version is offline and this calendar does not seem to be further developed,

you might want to try our [trello calendar](http://calendar-for-trello.com/) (hosted version) + [git repository](https://github.com/w11k/calendar-for-trello)
